# Non linear fit in Python

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

In [48]:
def func(p, a, b, c): 
    return a*p[0] + b*(p[0]/(p[0]+p[1]+p[2]))+c

In [49]:
p_1_data = [6799, 7999, 7999, 7999]
p_2_data = [10199, 10799, 10199, 11999]
p_3_data = [10199, 10799, 10199, 11999]
s_1_data = [3, 2.3, 2.2, 2.2]
s_2_data = [8, 5, 7.5, 3]
s_3_data = [6, 3, 5.6, 1.3]

xdata = np.vstack((p_1_data, p_2_data, p_3_data))

s_1_data = np.array(s_1_data)


In [50]:
print(xdata)
print(s_1_data)

[[ 6799  7999  7999  7999]
 [10199 10799 10199 11999]
 [10199 10799 10199 11999]]
[ 3.   2.3  2.2  2.2]


In [51]:
popt, pcov = curve_fit(func, xdata, s_1_data)

In [58]:
print (' fit coefficients (a, b, c):\n', popt)

 fit coefficients (a, b, c):
 [ -6.47154460e-04   5.72580624e-01   7.25686328e+00]


In [70]:
for i in range(0,4):
    print(func(xdata[:,i], popt[0], popt[1], popt[2]), ' Expected value: ', s_1_data[i])
    
#print(func(xdata[:,1], popt[0], popt[1], popt[2]), ' Expected value: ', s_1_data[1])
#print(func(xdata[:,2], popt[0], popt[1], popt[2]), ' Expected value: ', s_1_data[2])
#print(func(xdata[:,3], popt[0], popt[1], popt[2]), ' Expected value: ', s_1_data[3])

3.0  Expected value:  3.0
2.23502261497  Expected value:  2.3
2.24156194771  Expected value:  2.2
2.22341543731  Expected value:  2.2
