# Non linear fit in Python

Note: this example has been taken from a post I wrote on stackoverflow when I explain a poster how to do non linear fit in Python (Link: https://stackoverflow.com/questions/45033230/multivariate-linear-regression-using-a-defined-function-on-python)

In [3]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

We need to define a function that we will use for fitting our data. In this example `p` is an array containing our input values (sometimes indicated as `x`). In our function we will not do any sanity check (for example if all components of `p` are numbers and so on). This can be done by `curve_fit` using the parameter `check_finite` (Check the documentation [scipy.curve_fit documentation](https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.optimize.curve_fit.html)). The fit parameters are in this example `a,b,c`. 

In [4]:
def func(p, a, b, c): 
    return a*p[0] + b*(p[0]/(p[0]+p[1]+p[2]))+c

Now let's create some fake data. Our `p_*` arrays will be our input data, and `s_1` will be our expected output. After having defined the data as Python lists, we will convert to numpy arrays.

In [5]:
p_1_data = [6799, 7999, 7999, 7999]
p_2_data = [10199, 10799, 10199, 11999]
p_3_data = [10199, 10799, 10199, 11999]
s_1_data = [3, 2.3, 2.2, 2.2]

xdata = np.vstack((p_1_data, p_2_data, p_3_data))
s_1_data = np.array(s_1_data)


Each column in xdata repsent an observation. So the first element in the first column would be p[0], the second p[1] and the third p[1]. The second column is a separate observation and so on.

In [6]:
print(xdata)
print(s_1_data)

[[ 6799  7999  7999  7999]
 [10199 10799 10199 11999]
 [10199 10799 10199 11999]]
[ 3.   2.3  2.2  2.2]


Now we do the actual fitting, calling the `curve_fit` function.

In [7]:
popt, pcov = curve_fit(func, xdata, s_1_data)

In the `popt` list we wil find the parameters found by the function, and in the `pcov` the covariance matrix.

Note that the algorithm uses the Levenberg-Marquardt algorithm through [leastsq](https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.optimize.leastsq.html#scipy.optimize.leastsq). Note that this algorithm can only deal with unconstrained problems.

In [8]:
print (' fit coefficients (a, b, c):\n', popt)

 fit coefficients (a, b, c):
 [ -6.47154460e-04   5.72580624e-01   7.25686328e+00]


Now let's check the predictions of our model and compare them with the expected values

In [15]:
for i in range(0,4):
    print('Predicted value: ', "%.2f" % func(xdata[:,i], popt[0], popt[1], popt[2]), '- Expected value: ', s_1_data[i])

Predicted value:  3.00 - Expected value:  3.0
Predicted value:  2.24 - Expected value:  2.3
Predicted value:  2.24 - Expected value:  2.2
Predicted value:  2.22 - Expected value:  2.2
